### ISSUE TITLE
Error running run.py

### ISSUE THREAD

**Issue by luangasparclemente** [salzberg-lab/bolotie#1]
I got this error when I tried to run. (args used --input --reference --outdir)

can not perform indexing, path finding, parents finding and plotting without provided clusters. You can use consensus calls to generate a tree and clusters
Running stages: clean, align, consensus

==================
Cleaning sequence names in all inputs
Traceback (most recent call last):
  File "/"DELETED"/run.py", line 761, in <module>
    main(sys.argv[1:])
  File "/"DELETED"/run.py", line 757, in main
    args.func(args)
  File "/"DELETED"/run.py", line 666, in wrapper
    clean(args)
  File "DELETED"/run.py", line 307, in clean
    with open(args.clusters,"r") as inFP:
TypeError: expected str, bytes or os.PathLike object, not NoneType

Any suggestions on how to resolve this issue?

Thanks!

**Comment by cpockrandt** [comment]
Hi @luangasparclemente,

thanks for trying it out and sorry for the late reply.

It seems that you have not passed clusters to the script. Bolotie requires you to have pre-assigned clusters for all the sequences to run. If you have any other questions, let us know.
