### ISSUE TITLE
The example data of COV-2 is needed

### ISSUE THREAD

**Issue by yankuosun** [salzberg-lab/bolotie#2]
Bolotie is great， I want to follow the example data and more detailed steps to learn this software. The previously shared data could not be reached. ftp://ftp.ccb.jhu.edu/pub/data/bolotie_sars_cov_2  Thank you

**Comment by cpockrandt** [comment]
Hi @yankuosun 

thanks for looking into bolotie. I just tried to reach the website, and it works fine for me. Can you please try again? If the problem persists for you, please let me know and we'll find another way to send you the data!
